/****************************************************************************

  (c) SYS TEC electronic GmbH, D-08468 Heinsdorfergrund, Am Windrad 2
      www.systec-electronic.com

  Project:      CANopen_V5

  Description:  CANopen Object Dictionary File

  -------------------------------------------------------------------------

                $RCSfile: $

                $Author: $

                $Revision: $  $Date: $

                $State: $

                Build Environment:
                    ...

  -------------------------------------------------------------------------

  Revision History:

    16-Aug-2016:    - automatically generated by OdbCommand.exe

****************************************************************************/


#define OBD_DEFINE_MACRO
#include "obdmacro.h"
#undef OBD_DEFINE_MACRO


//---------------------------------------------------------------------------
// Definition of the Object Dictionary
//---------------------------------------------------------------------------

OBD_BEGIN()

    OBD_BEGIN_PART_GENERIC()

        OBD_BEGIN_INDEX_ROM(0x1000, 1, NULL)
            OBD_SUBINDEX_ROM_VAR(0x1000,   0, kObdTypUInt32, kObdAccR, tObdUnsigned32, Device_type, 0x00000000)
        OBD_END_INDEX(0x1000)

        OBD_BEGIN_INDEX_ROM(0x1001, 1, NULL)
            OBD_SUBINDEX_RAM_VAR(0x1001,   0, kObdTypUInt8, kObdAccR, tObdUnsigned8, Error_register, 0x00)
        OBD_END_INDEX(0x1001)

        OBD_BEGIN_INDEX_ROM(0x1003, 6, EmcpCbPreDefinedErrorField)
            OBD_SUBINDEX_RAM_VAR(0x1003,   0, kObdTypUInt8, kObdAccRW, tObdUnsigned8, Number_of_errors, 0x00)
            OBD_SUBINDEX_RAM_VAR(0x1003,   1, kObdTypUInt32, kObdAccR, tObdUnsigned32, Standard_error_field1, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1003,   2, kObdTypUInt32, kObdAccR, tObdUnsigned32, Standard_error_field2, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1003,   3, kObdTypUInt32, kObdAccR, tObdUnsigned32, Standard_error_field3, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1003,   4, kObdTypUInt32, kObdAccR, tObdUnsigned32, Standard_error_field4, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1003,   5, kObdTypUInt32, kObdAccR, tObdUnsigned32, Standard_error_field5, 0x00000000)
        OBD_END_INDEX(0x1003)

        OBD_BEGIN_INDEX_ROM(0x1008, 1, NULL)
            OBD_SUBINDEX_ROM_VSTRING(0x1008,   0, kObdAccR, Manufacturer_device_name, "KeLi XK3101")
        OBD_END_INDEX(0x1008)

        OBD_BEGIN_INDEX_ROM(0x1009, 1, NULL)
            OBD_SUBINDEX_ROM_VSTRING(0x1009,   0, kObdAccR, Manufacturer_hardware_version, "V1.0")
        OBD_END_INDEX(0x1009)

        OBD_BEGIN_INDEX_ROM(0x100A, 1, NULL)
            OBD_SUBINDEX_ROM_VSTRING(0x100A,   0, kObdAccR, Manufacturer_software_version, "V1.0")
        OBD_END_INDEX(0x100A)

        OBD_BEGIN_INDEX_ROM(0x1010, 5, CcmCbStore)
            OBD_SUBINDEX_ROM_VAR(0x1010,   0, kObdTypUInt8, kObdAccR, tObdUnsigned8, Highest_sub_index_supported, 0x04)
            OBD_SUBINDEX_RAM_VAR(0x1010,   1, kObdTypUInt32, kObdAccRW, tObdUnsigned32, save_all_parameters, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1010,   2, kObdTypUInt32, kObdAccRW, tObdUnsigned32, save_communication_parameters, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1010,   3, kObdTypUInt32, kObdAccRW, tObdUnsigned32, save_application_parameters, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1010,   4, kObdTypUInt32, kObdAccRW, tObdUnsigned32, save_manufacturer_defined_parameters, 0x00000000)
        OBD_END_INDEX(0x1010)

        OBD_BEGIN_INDEX_ROM(0x1011, 5, CcmCbRestore)
            OBD_SUBINDEX_ROM_VAR(0x1011,   0, kObdTypUInt8, kObdAccR, tObdUnsigned8, Highest_sub_index_supported, 0x04)
            OBD_SUBINDEX_RAM_VAR(0x1011,   1, kObdTypUInt32, kObdAccRW, tObdUnsigned32, restore_all_parameters, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1011,   2, kObdTypUInt32, kObdAccRW, tObdUnsigned32, restore_communication_parameters, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1011,   3, kObdTypUInt32, kObdAccRW, tObdUnsigned32, restore_application_parameters, 0x00000000)
            OBD_SUBINDEX_RAM_VAR(0x1011,   4, kObdTypUInt32, kObdAccRW, tObdUnsigned32, restore_manufacturer_defined_parameters, 0x00000000)
        OBD_END_INDEX(0x1011)

        OBD_BEGIN_INDEX_ROM(0x1014, 1, EmcpCbConfigEmergencyId)
            OBD_SUBINDEX_RAM_VAR(0x1014,   0, kObdTypUInt32, kObdAccSRW, tObdUnsigned32, COB_ID_emergency_message, 0)
        OBD_END_INDEX(0x1014)

        OBD_BEGIN_INDEX_ROM(0x1015, 1, NULL)
            OBD_SUBINDEX_RAM_VAR(0x1015,   0, kObdTypUInt16, kObdAccSRW, tObdUnsigned16, inhibit_time_EMCY, 0x0000)
        OBD_END_INDEX(0x1015)

        OBD_BEGIN_INDEX_ROM(0x1017, 1, HbpCbConfigHeartbeat)
            OBD_SUBINDEX_RAM_VAR(0x1017,   0, kObdTypUInt16, kObdAccSRW, tObdUnsigned16, Producer_heartbeat_time, 0x0BB8)
        OBD_END_INDEX(0x1017)

        OBD_BEGIN_INDEX_ROM(0x1018, 5, NULL)
            OBD_SUBINDEX_ROM_VAR(0x1018,   0, kObdTypUInt8, kObdAccR, tObdUnsigned8, Highest_sub_index_supported, 0x04)
            OBD_SUBINDEX_ROM_VAR(0x1018,   1, kObdTypUInt32, kObdAccR, tObdUnsigned32, Vendor_ID, 0x00000000)
            OBD_SUBINDEX_ROM_VAR(0x1018,   2, kObdTypUInt32, kObdAccR, tObdUnsigned32, Product_code, 0x00000001)
            OBD_SUBINDEX_ROM_VAR(0x1018,   3, kObdTypUInt32, kObdAccR, tObdUnsigned32, Revision_number, 0x00000000)
            OBD_SUBINDEX_ROM_VAR(0x1018,   4, kObdTypUInt32, kObdAccR, tObdUnsigned32, Serial_number, 0x00000001)
        OBD_END_INDEX(0x1018)

        OBD_CREATE_RXPDO_COMMU(0x1400,   0, 0x80000000, 255, 0, 0)

        OBD_CREATE_RXPDO_MAPP(0x1600,   0, 0, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000)

        OBD_CREATE_TXPDO_COMMU(0x1800,   0, 0x80000000, 255, 0, 0)
        OBD_CREATE_TXPDO_COMMU(0x1801,   1, 0x80000000, 255, 0, 0)
        OBD_CREATE_TXPDO_COMMU(0x1802,   2, 0x80000000, 255, 0, 0)
        OBD_CREATE_TXPDO_COMMU(0x1803,   3, 0x80000000, 255, 0, 0)

        OBD_CREATE_TXPDO_MAPP(0x1A00,   0, 0, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000)
        OBD_CREATE_TXPDO_MAPP(0x1A01,   1, 0, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000)
        OBD_CREATE_TXPDO_MAPP(0x1A02,   2, 0, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000)
        OBD_CREATE_TXPDO_MAPP(0x1A03,   3, 0, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000)

    OBD_END_PART()

    OBD_BEGIN_PART_MANUFACTURER()

        OBD_BEGIN_INDEX_ROM(0x2000, 1, NULL)
            OBD_SUBINDEX_RAM_USERDEF_NOINIT(0x2000,   0, kObdTypUInt8, kObdAccSRW, tObdUnsigned8, bBaudrate_g)
        OBD_END_INDEX(0x2000)

        OBD_BEGIN_INDEX_ROM(0x2001, 1, NULL)
            OBD_SUBINDEX_RAM_VAR(0x2001,   0, kObdTypUInt8, kObdAccSRW, tObdUnsigned8, Node_id, 0x01)
        OBD_END_INDEX(0x2001)

        OBD_BEGIN_INDEX_ROM(0x3000, 1, NULL)
            OBD_SUBINDEX_RAM_EXTVAR(0x3000,   0, kObdTypUInt8, kObdAccRW, tObdUnsigned8, bTare_CMD_g, 0x00)
        OBD_END_INDEX(0x3000)

        OBD_BEGIN_INDEX_ROM(0x3001, 1, NULL)
            OBD_SUBINDEX_RAM_EXTVAR(0x3001,   0, kObdTypUInt8, kObdAccRW, tObdUnsigned8, bqingpi_CMD_g, 0x00)
        OBD_END_INDEX(0x3001)

        OBD_BEGIN_INDEX_ROM(0x3002, 1, NULL)
            OBD_SUBINDEX_RAM_EXTVAR(0x3002,   0, kObdTypUInt8, kObdAccRW, tObdUnsigned8, bZero_CMD_g, 0x00)
        OBD_END_INDEX(0x3002)

        OBD_BEGIN_INDEX_ROM(0x4000, 1, NULL)
